all : Download Unzip validate

Download:
	wget -c https://www.googledrive.com/host/0Bz7lWLS0atxsalZSQWc1NXV2ajg
	

Unzip:
	mv '0Bz7lWLS0atxsalZSQWc1NXV2ajg' 'ds113_sub004.tgz'
	tar -zxvf ds113_sub004.tgz 

validate:
	python data.py


	